package app

var sentences = []string{
	"The quick brown fox jumps over the lazy dog.",
	"Never underestimate the power of a good book.",
	"To be or not to be, that is the question.",
	"The only thing we have to fear is fear itself.",
	"Ask not what your country can do for you, ask what you can do for your country.",
	"A journey of a thousand miles begins with a single step.",
	"Success is not final, failure is not fatal: it is the courage to continue that counts.",
	"The future belongs to those who believe in the beauty of their dreams.",
	"You must be the change you wish to see in the world.",
	"An investment in knowledge pays the best interest.",
	"The early bird catches the worm.",
	"Technology is best when it brings people together.",
	"I have not failed. I've just found 10,000 ways that won't work.",
	"The purpose of our lives is to be happy.",
	"Get busy living or get busy dying.",
	"Life is what happens when you're busy making other plans.",
	"The world is a book and those who do not travel read only one page.",
	"You only live once, but if you do it right, once is enough.",
	"To live is the rarest thing in the world. Most people exist, that is all.",
	"It is never too late to be what you might have been.",
	"Everything you can imagine is real.",
	"Simplicity is the ultimate sophistication. ",
	"Whatever you are, be a good one.",
	"Be yourself; everyone else is already taken.",
	"We are all in the gutter, but some of us are looking at the stars.",
	"The greatest glory in living lies not in never falling, but in rising every time we fall.",
	"To handle yourself, use your head; to handle others, use your heart.",
	"If you want to live a happy life, tie it to a goal, not to people or things.",
	"Your time is limited, so don't waste it living someone else's life.",
	"The best way to predict the future is to invent it.",
	"If you look at what you have in life, you'll always have more.",
	"The journey is the reward.",
	"Life is either a daring adventure or nothing at all.",
	"Many of life's failures are people who did not realize how close they were to success when they gave up.",
	"What may be the biggest battle yet in Donald Trump's trade war is about to begin.",
	"The Trump administration heads to the US Supreme Court on Wednesday, facing off against small businesses and a group of states who contend most of the tariffs it has put in place are illegal and should be struck down.",
	"If the court agrees with them, Trump's trade strategy would be upended, including the sweeping global tariffs he first announced in April.",
	"The government would also likely have to refund some of the billions of dollars it has collected through the tariffs, which are taxes on imports.",
	"The final decision from the justices will come after what could be months of poring over the arguments and discussing the merits of the case.",
	"Eventually they will hold a vote.",
	"Trump has described the fight in epic terms, warning a loss would tie his hands in trade negotiations and imperil national security.",
	"On Sunday, the president said he will not attend the hearing in person as he did not want to cause a distraction.",
	"I wanted to go so badly... I just don't want to do anything to deflect the importance of that decision,",
	"It's not about me, it's about our country.",
	"Trump previously said that if he does not win the case the US will be 'weakened' and in a 'financial mess' for many years to come.",
	"The stakes feel just as high for many businesses in the US and abroad, which have been paying the price while getting whipped about by fast-changing policies.",
	"Trump's tariffs will cost Learning Resources, a US seller of toys made mostly overseas and one of the businesses suing the government, $14m (£10.66m) this year.",
	"That is seven times what it spent on tariffs in 2024, according to CEO Rick Woldenberg.",
	"They've thrown our business into unbelievable disruption,",
	"Few businesses, though, are banking on a win at the court.",
	"We are hopeful that this is going to be ruled illegal but we're all also trying to prepare that it's setting in,",
	"His co-op, which imports coffee from more than a dozen countries, has already paid roughly $1.3m in tariffs since April.",
	"In deciding this case, the Supreme Court will have to take on a broader question: How far does presidential power go?",
	"Legal analysts say it is hard to predict the justices' answer, but a ruling siding with Trump will give him and future White House occupants greater reach.",
	"Specifically, the case concerns tariffs that the Trump administration imposed using the 1977 International Emergency Economic Powers Act (IEEPA), which the White House has embraced for its speed and flexibility.",
	"By declaring an emergency under the law, Trump can issue immediate orders and bypass longer, established processes.",
	"Trump first invoked the law in February to tax goods from China, Mexico and Canada, saying drug trafficking from those countries constituted an emergency.",
	"He deployed it again in April, ordering levies ranging from 10% to 50% on goods from almost every country in the world.",
	"This time, he said the US trade deficit - where the US imports more than it exports - posed an 'extraordinary and unusual threat'.",
	"Those tariffs took hold in fits and starts this summer while the US pushed countries to strike 'deals'.",
	"Opponents say the law authorises the president to regulate trade but never mentions the word 'tariffs', and they contend that only Congress can establish taxes under the US Constitution.",
	"They have also challenged whether the issues cited by the White House, especially the trade deficit, represent emergencies.",
	"Members of Congress from both parties have asserted the Constitution gives them responsibility for creating tariffs, duties and taxes, as well.",
	"More than 200 Democrats in both chambers and one Republican, Senator Lisa Murkowski, filed a brief to the Supreme Court, where they also argued the emergency law did not grant the president power to use tariffs as a tool for gaining leverage in trade talks.",
	"Meanwhile, last week the Senate made a symbolic and bipartisan move to pass three resolutions rejecting Trump's tariffs, including one to end the national emergency he declared.",
	"They are not expected to be approved in the House.",
	"Still, business groups said they hoped the rebuke would send a message to the justices.",
	"Three lower courts have ruled against the administration.",
	"After the Supreme Court hears arguments on Wednesday it will have until June to issue its decision, although most expect a ruling to come by January.",
	"Whatever it decides has implications for an estimated $90bn worth of import taxes already paid - roughly half the tariff revenue the US collected this year through September, according to Wells Fargo analysts.",
	"Trump officials have warned that sum could swell to $1tn if the court takes until June.",
	"If the government is forced to issue refunds, Cooperative Coffees will 'absolutely' try to recoup its money, said Mr Harris, but that would not make up for all the disruption.",
	"His business has had to take out an extra line of credit, raise prices and find ways to survive with lower profits.",
	"This is an energy drain like I've never seen,",
	"It dominates all the conversations and it just kind of sucks the life out of you.",
	"The White House says that if it loses, it will impose levies via other means, such as a law allowing the president to put tariffs of up to 15% in place for 150 days.",
	"Even then, businesses would have some relief, since those other means require steps like issuing formal notices, which take time and deliberation, said trade lawyer Ted Murphy of Sidley Austin.",
	"This is not just about the money,",
	"The president has announced tariffs on Sunday that go into effect on Wednesday, without advance notice, without any real process.",
	"I think that's the bigger thing for this case for businesses - whether or not that is going to be in our future,",
	"There is no clear sign of how the court will rule.",
	"In recent years it has struck down major policies, such as Biden-era student loan forgiveness, as White House overreach.",
	"But the nine justices, six of whom were appointed by Republicans, including three by Trump, have shown deference to this president in other recent disputes and historically have given leeway to the White House on questions of national security.",
	"I really do think arguments are available for the Supreme Court to go in all different directions,",
	"Adam White, senior fellow at the American Enterprise Institute, said he expected the court to strike down the tariffs, but avoid questions like what constitutes a national emergency.",
	"The case has already complicated the White House's trade deals, such as one struck in July with the European Union.",
	"The European Parliament is currently considering ratifying the agreement, which sets US tariffs on European goods at 15% in exchange for promises including allowing in more US agricultural products.",
	"They're not going to act on this until they see the outcome of the Supreme Court decision,",
	"In Switzerland, which recently downgraded its outlook for economic growth citing America’s 39% tariff on its goods, chocolatier Daniel Bloch said he'd welcome a ruling against the Trump administration.",
	"His business Chocolats Camille Bloch is absorbing about a third of the cost of new tariffs on kosher chocolate that his firm has exported to the US for decades, aiming to blunt price increases and maintain sales.",
	"That decision has wiped out profits for the unit and is not sustainable, he said.",
	"He hopes Trump will reconsider his tariffs altogether, because 'that would be easiest'.",
	"If the court were to make the tariffs go away of course we would see that as a positive sign,",
	"But we don't trust that that will bring the solution.",
	"A monkey moves around in grass",
	"Mississippi mum fatally shoots escaped research monkey",
	"The mother of five says she feared for the safety of her children, after hearing the escaped monkeys carried diseases.",
	"Trump says he doubts US will go to war with Venezuela",
	"The US president also suggests Nicolás Maduro's days as the South American country's leader are numbered.",
	"Trump tells military to prepare for 'action' against Islamist militants in Nigeria",
	"The US president says his threat is over killings of Christians - though experts say there is no evidence they are disproportionately targeted.",
	"City's exports 'slow' after JLR attack and tariffs",
	"Greater Birmingham Chambers of Commerce say a report reveals a challenging latest quarter for exporters.",
	"Clooney says Harris replacing Biden was a 'mistake'",
	"The actor - a prominent Democratic fundraiser - also says he has no regrets about calling for Biden to quit the US presidential race.",
    "Should K-beauty products have to come from South Korea?",
    "Korean skincare or 'K-beauty' products are very popular around the world.",
    "But as exports from South Korea hit $10.3bn (£7.7bn) last year, cosmetics companies in other countries have introduced their own K-beauty ranges that are not Korean-made.",
    "Does this blurring of the definition matter?",
    "K-beauty products first came to international attention in the 2010s, part of a wave of other Korean exports, such as K-pop and K-drama.",
    "The K-beauty skincare regime can be very elaborate, involving as many as 10 different steps, each requiring a separate product.",
    "This caught the imagination of people around the world, and sales rose sharply.",
    "Annual exports from South Korea increased from $650m in 2011 to $4bn in 2017, according to official figures, a sixfold rise in just six years.",
    "Recognising this huge jump in demand, cosmetics brand Seoul Ceuticals was launched in 2017, named after the South Korean capital.",
    "We started to see this increase in growth in interest in K-beauty, and began developing a skincare brand to meet that demand… when we really saw it emerging in the US,",
    "It has been extremely successful.",
    "We expect to do over $14m in sales in 2025.",
    "We've seen a global acceptance and demand for the K-beauty products.",
    "We've started selling in India, Latin America, Europe and Australia.",
    "But Seoul Ceuticals is not a Korean company.",
    "It is based in the US, where it also manufacturers all its products.",
    "The business doesn't claim to be Korean, but it does say that it makes 'real, authentic Korean skincare'.",
    "That may sound like a contradiction, but the company says it isn't because its ingredients are sourced from South Korea.",
    "I think we were a little more sensitive about it when we were first starting, because we wanted to be very transparent that the products are made in the US,",
    "[But] we source our ingredients in Korea… we wanted to be able to legitimately say we are a K-beauty brand.",
    "But not everyone would agree with this.",
    "The products should be manufactured by a Korean manufacturer,",
    "He runs the business with his wife Elisa Ahonpää-Kim.",
    "While they are based in Finland, all of their team except Elisa are Korean, and all their products are made in South Korea.",
    "The most important thing that we both absolutely agree is that the brand should develop its concept, and ideas, and products with a Korean perspective,",
    "That can come through in the ingredients, the design.",
    "Or cultural elements, basically anything that clearly connects to the brands to Korea, or at least reflects a Korean influence.",
    "However, the couple do admit that the definition of K-beauty remains complex.",
    "I guess it's a very vague concept, because on the market you will find a lot of brands that are made by Koreans who live abroad,",
    "And then brands like Lancôme and Clinique manufacture their products in Korea and Japan, but then it doesn't make those brands Japanese and Korean.",
    "There is currently no official definition of K-beauty.",
    "And there is no protected designation of origin to defend it, like in the case of Champagne or Parmigiano Reggiano cheese.",
    "And there is no plan to set one up, according to the K-beauty Industry Association, the only K-beauty trade body officially approved by the South Korean government.",
    "We are currently more focused in promoting and expanding K-beauty,",
    "While the trend is quite established in Asia, it is only just starting in Europe and the US, and we don't want to throttle the growth by imposing any sanctions on them.",
    "However, the association does have rules for its members – they must be companies that are registered in South Korea, and their products must be officially tested and approved by Korea Food & Drug Administration.",
    "That approval is required in order to sell inside South Korea.",
    "If a product is developed in a way that suits the climate and environment of Korea, and is recognized as a viable product in the Korean market, then we would acknowledge it as K-beauty,",
    "Hwarangpoom agrees with this definition, and has received approval from KFDA.",
    "And Seoul Ceuticals has also started the process to attain KFDA approval, to bring their products to Korean consumers.",
    "With K-beauty exports from South Korea in 2024 20% higher than in 2023, there is a lot of money to be made in the sector whether the firms are homegrown or not.",
    "In fact, South Korea is now the largest exporter of cosmetic products after France and the US.",
    "However, this success has spawned counterfeiters.",
    "Mark Lee is the CEO of MarqVision, a US-based business helps firms spot fakes and get them removed from sale.",
    "For a major Korean beauty brand, which I cannot disclose, we recently conducted 29 test purchases across major US marketplaces,",
    "Twenty six of them were fake.",
    "So that's a 90% counterfeit rate.",
    "And in 2024 as a whole, Marqvision identified $280m worth of fake K-beauty products in the US market alone.",
    "The high number of counterfeits greatly frustrated K-beauty fan Gracie Tullio.",
    "Shopping online for K-beauty was a really scary experience,",
    "This led to London-based Ms Tullio launching PureSeoul in 2019, a K-beauty retail business that sells authentic products sourced directly from Korean manufacturers.",
    "She says she gets customers who visit the shop with suspected fake products to check if they are real.",
    "Even our customers can be sometimes tempted by the lower price [of online fakes].",
    "It's so tempting for them just to give it a go and see, and nine times out of 10, it's not real,",
    "The striking Swedish workers taking on carmaker Tesla",
    "How the outsourcing sector became South Africa's newest goldmine",
    "Netherlands' renewables drive putting pressure on its power grid",
    "The indigenous weavers who aim for empowerment over exploitation",
    "Will AI mean the end of call centres?",
    "Mississippi mum fatally shoots escaped research monkey",
    "The mother of five says she feared for the safety of her children, after hearing the escaped monkeys carried diseases.",
    "Trump says he doubts US will go to war with Venezuela",
    "The US president also suggests Nicolás Maduro's days as the South American country's leader are numbered.",
    "Clooney says Harris replacing Biden was a 'mistake'",
    "The actor - a prominent Democratic fundraiser - also says he has no regrets about calling for Biden to quit the US presidential race.",
    "Trump's planned tests are 'not nuclear explosions', US energy secretary says",
    "Chris Wright says the tests will be 'non-critical explosions', meaning that Americans would not be seeing mushroom clouds.",
    "'No idea who he is,' says Trump after pardoning crypto tycoon",
    "The president pardoned Changpeng Zhao, the co-founder of the world's largest crypto exchange, in October.",
}
