package app

var sentences = []string{
	"The quick brown fox jumps over the lazy dog.",
	"Never underestimate the power of a good book.",
	"To be or not to be, that is the question.",
	"The only thing we have to fear is fear itself.",
	"Ask not what your country can do for you, ask what you can do for your country.",
	"A journey of a thousand miles begins with a single step.",
	"Success is not final, failure is not fatal: it is the courage to continue that counts.",
	"The future belongs to those who believe in the beauty of their dreams.",
	"You must be the change you wish to see in the world.",
	"An investment in knowledge pays the best interest.",
	"The early bird catches the worm.",
	"Technology is best when it brings people together.",
	"I have not failed. I've just found 10,000 ways that won't work.",
	"The purpose of our lives is to be happy.",
	"Get busy living or get busy dying.",
	"Life is what happens when you're busy making other plans.",
	"The world is a book and those who do not travel read only one page.",
	"You only live once, but if you do it right, once is enough.",
	"To live is the rarest thing in the world. Most people exist, that is all.",
	"It is never too late to be what you might have been.",
	"Everything you can imagine is real.",
	"Simplicity is the ultimate sophistication. ",
	"Whatever you are, be a good one.",
	"Be yourself; everyone else is already taken.",
	"We are all in the gutter, but some of us are looking at the stars.",
	"The greatest glory in living lies not in never falling, but in rising every time we fall.",
	"To handle yourself, use your head; to handle others, use your heart.",
	"If you want to live a happy life, tie it to a goal, not to people or things.",
	"Your time is limited, so don't waste it living someone else's life.",
	"The best way to predict the future is to invent it.",
	"If you look at what you have in life, you'll always have more.",
	"The journey is the reward.",
	"Life is either a daring adventure or nothing at all.",
	"Many of life's failures are people who did not realize how close they were to success when they gave up.",
	"What may be the biggest battle yet in Donald Trump's trade war is about to begin.",
	"The Trump administration heads to the US Supreme Court on Wednesday, facing off against small businesses and a group of states who contend most of the tariffs it has put in place are illegal and should be struck down.",
	"If the court agrees with them, Trump's trade strategy would be upended, including the sweeping global tariffs he first announced in April.",
	"The government would also likely have to refund some of the billions of dollars it has collected through the tariffs, which are taxes on imports.",
	"The final decision from the justices will come after what could be months of poring over the arguments and discussing the merits of the case.",
	"Eventually they will hold a vote.",
	"Trump has described the fight in epic terms, warning a loss would tie his hands in trade negotiations and imperil national security.",
	"On Sunday, the president said he will not attend the hearing in person as he did not want to cause a distraction.",
	"I wanted to go so badly... I just don't want to do anything to deflect the importance of that decision,",
	"It's not about me, it's about our country.",
	"Trump previously said that if he does not win the case the US will be 'weakened' and in a 'financial mess' for many years to come.",
	"The stakes feel just as high for many businesses in the US and abroad, which have been paying the price while getting whipped about by fast-changing policies.",
	"Trump's tariffs will cost Learning Resources, a US seller of toys made mostly overseas and one of the businesses suing the government, $14m (£10.66m) this year.",
	"That is seven times what it spent on tariffs in 2024, according to CEO Rick Woldenberg.",
	"They've thrown our business into unbelievable disruption,",
	"Few businesses, though, are banking on a win at the court.",
	"We are hopeful that this is going to be ruled illegal but we're all also trying to prepare that it's setting in,",
	"His co-op, which imports coffee from more than a dozen countries, has already paid roughly $1.3m in tariffs since April.",
	"In deciding this case, the Supreme Court will have to take on a broader question: How far does presidential power go?",
	"Legal analysts say it is hard to predict the justices' answer, but a ruling siding with Trump will give him and future White House occupants greater reach.",
	"Specifically, the case concerns tariffs that the Trump administration imposed using the 1977 International Emergency Economic Powers Act (IEEPA), which the White House has embraced for its speed and flexibility.",
	"By declaring an emergency under the law, Trump can issue immediate orders and bypass longer, established processes.",
	"Trump first invoked the law in February to tax goods from China, Mexico and Canada, saying drug trafficking from those countries constituted an emergency.",
	"He deployed it again in April, ordering levies ranging from 10% to 50% on goods from almost every country in the world.",
	"This time, he said the US trade deficit - where the US imports more than it exports - posed an 'extraordinary and unusual threat'.",
	"Those tariffs took hold in fits and starts this summer while the US pushed countries to strike 'deals'.",
	"Opponents say the law authorises the president to regulate trade but never mentions the word 'tariffs', and they contend that only Congress can establish taxes under the US Constitution.",
	"They have also challenged whether the issues cited by the White House, especially the trade deficit, represent emergencies.",
	"Members of Congress from both parties have asserted the Constitution gives them responsibility for creating tariffs, duties and taxes, as well.",
	"More than 200 Democrats in both chambers and one Republican, Senator Lisa Murkowski, filed a brief to the Supreme Court, where they also argued the emergency law did not grant the president power to use tariffs as a tool for gaining leverage in trade talks.",
	"Meanwhile, last week the Senate made a symbolic and bipartisan move to pass three resolutions rejecting Trump's tariffs, including one to end the national emergency he declared.",
	"They are not expected to be approved in the House.",
	"Still, business groups said they hoped the rebuke would send a message to the justices.",
	"Three lower courts have ruled against the administration.",
	"After the Supreme Court hears arguments on Wednesday it will have until June to issue its decision, although most expect a ruling to come by January.",
	"Whatever it decides has implications for an estimated $90bn worth of import taxes already paid - roughly half the tariff revenue the US collected this year through September, according to Wells Fargo analysts.",
	"Trump officials have warned that sum could swell to $1tn if the court takes until June.",
	"If the government is forced to issue refunds, Cooperative Coffees will 'absolutely' try to recoup its money, said Mr Harris, but that would not make up for all the disruption.",
	"His business has had to take out an extra line of credit, raise prices and find ways to survive with lower profits.",
	"This is an energy drain like I've never seen,",
	"It dominates all the conversations and it just kind of sucks the life out of you.",
	"The White House says that if it loses, it will impose levies via other means, such as a law allowing the president to put tariffs of up to 15% in place for 150 days.",
	"Even then, businesses would have some relief, since those other means require steps like issuing formal notices, which take time and deliberation, said trade lawyer Ted Murphy of Sidley Austin.",
	"This is not just about the money,",
	"The president has announced tariffs on Sunday that go into effect on Wednesday, without advance notice, without any real process.",
	"I think that's the bigger thing for this case for businesses - whether or not that is going to be in our future,",
	"There is no clear sign of how the court will rule.",
	"In recent years it has struck down major policies, such as Biden-era student loan forgiveness, as White House overreach.",
	"But the nine justices, six of whom were appointed by Republicans, including three by Trump, have shown deference to this president in other recent disputes and historically have given leeway to the White House on questions of national security.",
	"I really do think arguments are available for the Supreme Court to go in all different directions,",
	"Adam White, senior fellow at the American Enterprise Institute, said he expected the court to strike down the tariffs, but avoid questions like what constitutes a national emergency.",
	"The case has already complicated the White House's trade deals, such as one struck in July with the European Union.",
	"The European Parliament is currently considering ratifying the agreement, which sets US tariffs on European goods at 15% in exchange for promises including allowing in more US agricultural products.",
	"They're not going to act on this until they see the outcome of the Supreme Court decision,",
	"In Switzerland, which recently downgraded its outlook for economic growth citing America’s 39% tariff on its goods, chocolatier Daniel Bloch said he'd welcome a ruling against the Trump administration.",
	"His business Chocolats Camille Bloch is absorbing about a third of the cost of new tariffs on kosher chocolate that his firm has exported to the US for decades, aiming to blunt price increases and maintain sales.",
	"That decision has wiped out profits for the unit and is not sustainable, he said.",
	"He hopes Trump will reconsider his tariffs altogether, because 'that would be easiest'.",
	"If the court were to make the tariffs go away of course we would see that as a positive sign,",
	"But we don't trust that that will bring the solution.",
	"A monkey moves around in grass",
	"Mississippi mum fatally shoots escaped research monkey",
	"The mother of five says she feared for the safety of her children, after hearing the escaped monkeys carried diseases.",
	"Trump says he doubts US will go to war with Venezuela",
	"The US president also suggests Nicolás Maduro's days as the South American country's leader are numbered.",
	"Trump tells military to prepare for 'action' against Islamist militants in Nigeria",
	"The US president says his threat is over killings of Christians - though experts say there is no evidence they are disproportionately targeted.",
	"City's exports 'slow' after JLR attack and tariffs",
	"Greater Birmingham Chambers of Commerce say a report reveals a challenging latest quarter for exporters.",
	"Clooney says Harris replacing Biden was a 'mistake'",
	"The actor - a prominent Democratic fundraiser - also says he has no regrets about calling for Biden to quit the US presidential race.",
}