package app

var sentences = []string{
	"The quick brown fox jumps over the lazy dog.",
	"Never underestimate the power of a good book.",
	"To be or not to be, that is the question.",
	"The only thing we have to fear is fear itself.",
	"Ask not what your country can do for you, ask what you can do for your country.",
	"A journey of a thousand miles begins with a single step.",
	"Success is not final, failure is not fatal: it is the courage to continue that counts.",
	"The future belongs to those who believe in the beauty of their dreams.",
	"You must be the change you wish to see in the world.",
	"An investment in knowledge pays the best interest.",
	"The early bird catches the worm.",
	"Technology is best when it brings people together.",
	"I have not failed. I've just found 10,000 ways that won't work.",
	"The purpose of our lives is to be happy.",
	"Get busy living or get busy dying.",
	"Life is what happens when you're busy making other plans.",
	"The world is a book and those who do not travel read only one page.",
	"You only live once, but if you do it right, once is enough.",
	"To live is the rarest thing in the world. Most people exist, that is all.",
	"It is never too late to be what you might have been.",
	"Everything you can imagine is real.",
	"Simplicity is the ultimate sophistication. ",
	"Whatever you are, be a good one.",
	"Be yourself; everyone else is already taken.",
	"We are all in the gutter, but some of us are looking at the stars.",
	"The greatest glory in living lies not in never falling, but in rising every time we fall.",
	"To handle yourself, use your head; to handle others, use your heart.",
	"If you want to live a happy life, tie it to a goal, not to people or things.",
	"Your time is limited, so don't waste it living someone else's life.",
	"The best way to predict the future is to invent it.",
	"If you look at what you have in life, you'll always have more.",
	"The journey is the reward.",
	"Life is either a daring adventure or nothing at all.",
	"Many of life's failures are people who did not realize how close they were to success when they gave up.",
}
