package domain

// Sentences is the pool of English typing targets, grouped by theme. They are
// kept varied in length so both quick rounds and longer runs feel natural.
var Sentences = []string{
	// Famous Quotes
	"The quick brown fox jumps over the lazy dog.",
	"Never underestimate the power of a good book.",
	"To be or not to be, that is the question.",
	"The only thing we have to fear is fear itself.",
	"Ask not what your country can do for you, ask what you can do for your country.",
	"A journey of a thousand miles begins with a single step.",
	"Success is not final, failure is not fatal: it is the courage to continue that counts.",
	"The future belongs to those who believe in the beauty of their dreams.",
	"You must be the change you wish to see in the world.",
	"An investment in knowledge pays the best interest.",
	"The early bird catches the worm.",
	"Technology is best when it brings people together.",
	"I have not failed. I've just found 10,000 ways that won't work.",
	"The purpose of our lives is to be happy.",
	"Get busy living or get busy dying.",
	"Life is what happens when you're busy making other plans.",
	"The world is a book and those who do not travel read only one page.",
	"You only live once, but if you do it right, once is enough.",
	"To live is the rarest thing in the world. Most people exist, that is all.",
	"It is never too late to be what you might have been.",
	"Everything you can imagine is real.",
	"Simplicity is the ultimate sophistication.",
	"Whatever you are, be a good one.",
	"Be yourself; everyone else is already taken.",
	"We are all in the gutter, but some of us are looking at the stars.",
	"The greatest glory in living lies not in never falling, but in rising every time we fall.",
	"To handle yourself, use your head; to handle others, use your heart.",
	"If you want to live a happy life, tie it to a goal, not to people or things.",
	"Your time is limited, so don't waste it living someone else's life.",
	"The best way to predict the future is to invent it.",
	"If you look at what you have in life, you'll always have more.",
	"The journey is the reward.",
	"Life is either a daring adventure or nothing at all.",
	"Many of life's failures are people who did not realize how close they were to success when they gave up.",

	// Programming Quotes
	"Talk is cheap. Show me the code.",
	"Programs must be written for people to read, and only incidentally for machines to execute.",
	"Truth can only be found in one place: the code.",
	"Deleted code is debugged code.",
	"Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
	"First, solve the problem. Then, write the code.",
	"Experience is the name everyone gives to their mistakes.",
	"Code is like humor. When you have to explain it, it's bad.",
	"Fix the cause, not the symptom.",
	"Optimism is an occupational hazard of programming: feedback is the treatment.",
	"Simplicity is the soul of efficiency.",
	"Before software can be reusable it first has to be usable.",
	"Make it work, make it right, make it fast.",
	"Premature optimization is the root of all evil.",
	"There are only two hard things in computer science: cache invalidation and naming things.",
	"Weeks of coding can save you hours of planning.",
	"A good name for a variable is worth a thousand comments.",
	"Test your code, or your users will do it for you.",
	"The best error message is the one that never shows up.",
	"Refactoring is improving code without changing what it does.",
	"Version control is a time machine for your mistakes.",
	"Read the documentation before you ask the question.",
	"A function should do one thing and do it well.",
	"Commit small, commit often, and write a clear message.",
	"Every dependency you add is a promise you have to keep.",
	"Delete the code you do not need; it cannot break.",
	"Name things for what they do, not how they do it.",
	"Logs are love letters you write to your future self.",
	"If it is not tested, assume it is broken.",
	"Reading code is harder than writing it, so write it kindly.",

	// Pangrams
	"Pack my box with five dozen liquor jugs.",
	"How vexingly quick daft zebras jump!",
	"The five boxing wizards jump quickly.",
	"Sphinx of black quartz, judge my vow.",
	"Waltz, bad nymph, for quick jigs vex.",
	"Jackdaws love my big sphinx of quartz.",
	"Two driven jocks help fax my big quiz.",
	"The job requires extra pluck and zeal from every young wage earner.",
	"Crazy Fredrick bought many very exquisite opal jewels.",
	"We promptly judged antique ivory buckles for the next prize.",

	// Everyday sentences
	"The morning sun spilled gold across the quiet harbor.",
	"She packed a thermos of coffee and headed for the trail.",
	"Rain tapped softly against the window all afternoon.",
	"A warm loaf of bread cooled on the kitchen counter.",
	"The train arrived exactly on time for once.",
	"He folded the map and tucked it into his jacket.",
	"Bring an umbrella; the forecast looks uncertain.",
	"The library smelled of old paper and quiet patience.",
	"We watched the storm roll in from the porch.",
	"A single candle lit the entire room.",
	"The kettle whistled just as the phone began to ring.",
	"Leaves drifted down and gathered along the fence.",
	"Her notebook was full of half-finished ideas.",
	"The old clock on the wall was always five minutes slow.",
	"They planted tomatoes and basil in the back garden.",
	"A cool breeze carried the smell of the sea.",
	"The cat stretched and claimed the warmest chair.",
	"Streetlights flickered on one by one at dusk.",
	"He sketched the bridge while the river slid by.",
	"The bakery sold out of croissants before nine.",

	// Practice maxims (short to medium)
	"Practice a little every day and progress will follow.",
	"Slow is smooth, and smooth is fast.",
	"Measure twice, cut once.",
	"Good habits are built one small choice at a time.",
	"Curiosity is the engine of every great discovery.",
	"Fortune favors the bold.",
	"Knowledge speaks, but wisdom listens.",
	"What gets measured gets managed.",
	"Perfect is the enemy of good.",
	"Hope for the best, but prepare for the worst.",
	"When in doubt, leave it out.",
	"A smooth sea never made a skilled sailor.",
	"The pen is mightier than the sword.",
	"Done is better than perfect.",
	"Less is more.",
	"Keep it simple.",
	"One step at a time.",
	"Trust the process.",
	"Actions speak louder than words.",
	"Look before you leap.",
	"Still waters run deep.",
	"Every cloud has a silver lining.",
	"Well begun is half done.",
	"Mind over matter.",
	"Easy come, easy go.",
}
